server:
   port: 1000 
 
spring: 
   application:
      name: service-a
    
management: 
   endpoints: 
      web: 
         exposure:
            include: 
               - "*"
feign: 
   hystrix: 
      enabled: true
      
eureka: 
  instance:   
     prefer-ip-address: true 