server:
   port: 8080 
 
spring: 
   application:
      name: item-inventory
   jpa: 
      generate-ddl: true 
   h2: 
      console: 
         enabled: true 
   datasource: 
      url: jdbc:h2:mem:itemDB   
      
   data:
      mongodb:
         database: aspireTrainingDb
         uri: mongodb://localhost:27017/itemInventory

management: 
   endpoints: 
      web: 
         exposure:
            include: 
               - "*"
feign: 
   hystrix: 
      enabled: true
      
eureka: 
  instance:   
     prefer-ip-address: true 
        
com:
   aspire:
      training:
         error-Msgs: 
            ItemNotFoundException: 
               errorCode: 1 
               restStatus: 404 
               msgs: 
                  AR: "arabic Item not found"
                  EN: "Item not found"
                                  
db: 
   in-memory:
      enabled: false 
   RDS: 
      enabled: false    
   mongo:
      enabled: true